#pragma once

#define MATRIX_ROW_PULLS MATRIX_PULL_DOWN
#define MATRIX_COL_PULLS MATRIX_PULL_DOWN
#define NUM_ENCODERS 2

#undef TAPPING_TERM
#define TAPPING_TERM 200
#ifndef QUICK_TAP_TERM_PER_KEY
    #define QUICK_TAP_TERM_PER_KEY
#endif
#define QUICK_TAP_TERM 120
#ifndef PERMISSIVE_HOLD_PER_KEY
    #define PERMISSIVE_HOLD_PER_KEY
#endif
#define BOTH_SHIFTS_TURNS_ON_CAPS_WORD

#undef MOUSEKEY_DELAY
#define MOUSEKEY_DELAY          0
#undef MOUSEKEY_INTERVAL
#define MOUSEKEY_INTERVAL       16
#undef MOUSEKEY_WHEEL_DELAY
#define MOUSEKEY_WHEEL_DELAY    0
#undef MOUSEKEY_MAX_SPEED
#define MOUSEKEY_MAX_SPEED      6
#undef MOUSEKEY_TIME_TO_MAX
#define MOUSEKEY_TIME_TO_MAX    64