#pragma once

#define MATRIX_ROW_PULLS MATRIX_PULL_DOWN
#define MATRIX_COL_PULLS MATRIX_PULL_DOWN
#define NUM_ENCODERS 2

#define BOTH_SHIFTS_TURNS_ON_CAPS_WORD
#undef TAPPING_TERM
#define TAPPING_TERM 200
#define PERMISSIVE_HOLD

#undef MOUSEKEY_DELAY
#define MOUSEKEY_DELAY          0
#undef MOUSEKEY_INTERVAL
#define MOUSEKEY_INTERVAL       16
#undef MOUSEKEY_WHEEL_DELAY
#define MOUSEKEY_WHEEL_DELAY    0
#undef MOUSEKEY_MAX_SPEED
#define MOUSEKEY_MAX_SPEED      6
#undef MOUSEKEY_TIME_TO_MAX
#define MOUSEKEY_TIME_TO_MAX    64